Update `TEST_CASE_VERSIONS_AUD` set `PRIORITY` = 'BLOCKER'
where `PRIORITY` = 'HIGH';
Update `TEST_CASE_VERSIONS_AUD` set `PRIORITY` = 'NORMAL'
where `PRIORITY` = 'MEDIUM';
Update `TEST_CASE_VERSIONS_AUD` set `PRIORITY` = 'MINOR'
where `PRIORITY` = 'LOW';
Update `TEST_CASE_VERSIONS_AUD` set `PRIORITY` = 'MINOR'
where `PRIORITY` = 'UNKNOWN';