CREATE TABLE IF NOT EXISTS `TEST_EXECUTIONS` (
  `id`           BIGINT   AUTO_INCREMENT,
  `test_plan_id` BIGINT   NOT NULL,
  `test_case_id` BIGINT   NOT NULL,
  `created_at`   DATETIME NOT NULL,
  `author_id`    BIGINT   NULL DEFAULT NULL,
  `result`       TINYINT  NOT NULL,
  `comment`      TEXT     NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_TEST_EXECUTIONS_TEST_PLANS`
  FOREIGN KEY (`test_plan_id`)
  REFERENCES `TEST_PLANS` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_TEST_EXECUTIONS_TEST_CASES`
  FOREIGN KEY (`test_case_id`)
  REFERENCES `TEST_CASES` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_TEST_EXECUTIONS_USERS`
  FOREIGN KEY (`author_id`)
  REFERENCES `USERS` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
);

CREATE INDEX `FK_TEST_EXECUTIONS_TEST_PLANS_idx` ON `TEST_EXECUTIONS` (`test_plan_id` ASC);
CREATE INDEX `FK_TEST_EXECUTIONS_TEST_CASES_idx` ON `TEST_EXECUTIONS` (`test_case_id` ASC);
CREATE INDEX `FK_TEST_EXECUTIONS_USERS_idx` ON `TEST_EXECUTIONS` (`author_id` ASC);

CREATE TABLE IF NOT EXISTS `TEST_EXECUTIONS_AUD` (
  `id`           BIGINT   AUTO_INCREMENT,
  `test_plan_id` BIGINT   NOT NULL,
  `test_case_id` BIGINT   NOT NULL,
  `created_at`   DATETIME NOT NULL,
  `author_id`    BIGINT   NULL DEFAULT NULL,
  `result`       TINYINT  NOT NULL,
  `comment`      TEXT     NULL DEFAULT NULL,
  `REV`          INT      NOT NULL,
  `REVTYPE`      TINYINT  NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `REV`),
  CONSTRAINT `TEST_EXECUTIONS_AUD_AUDIT_REVISION_ENTITY`
  FOREIGN KEY (`REV`)
  REFERENCES `AUDIT_REVISION_ENTITY` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
);

CREATE INDEX `TEST_EXECUTIONS_AUD_AUDIT_REVISION_ENTITY_idx` ON `TEST_CASES_AUD` (`REV` ASC);
