ALTER TABLE `TEST_PLANS` ADD COLUMN `start_date`   DATETIME NULL;
ALTER TABLE `TEST_PLANS` ADD COLUMN `end_date`   DATETIME NULL;
ALTER TABLE `TEST_PLANS` ADD COLUMN `assigned_user_id`   BIGINT NULL DEFAULT NULL;
ALTER TABLE `TEST_PLANS` ADD COLUMN `system_version` TEXT NULL DEFAULT NULL;

ALTER TABLE `TEST_PLANS_AUD` ADD COLUMN `start_date`   DATETIME NOT NULL;
ALTER TABLE `TEST_PLANS_AUD` ADD COLUMN `end_date`   DATETIME NOT NULL;
ALTER TABLE `TEST_PLANS_AUD` ADD COLUMN `assigned_user_id`   BIGINT NULL DEFAULT NULL;
ALTER TABLE `TEST_PLANS_AUD` ADD COLUMN `system_version` TEXT NULL DEFAULT NULL;
