-- Table `DEFECTS`
CREATE TABLE IF NOT EXISTS `DEFECTS` (
  `id`               BIGINT       AUTO_INCREMENT,
  `deleted`          BOOLEAN      NULL DEFAULT FALSE,
  `external_id`      VARCHAR(255) NOT NULL,
  `external_title`   VARCHAR(255) NULL DEFAULT NULL,
  `external_summary` VARCHAR(255) NULL DEFAULT NULL,
  `project_id`       BIGINT       NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

CREATE UNIQUE INDEX `UK_DEFECTS` ON `DEFECTS` (`external_id` ASC);


-- Table `DEFECTS_AUD`
CREATE TABLE IF NOT EXISTS `DEFECTS_AUD` (
  `REV`              INT          NOT NULL,
  `REVTYPE`          TINYINT      NULL DEFAULT NULL,
  `id`               BIGINT       NOT NULL,
  `deleted`          BOOLEAN      NULL DEFAULT FALSE,
  `external_id`      VARCHAR(255) NULL DEFAULT NULL,
  `external_title`   VARCHAR(255) NULL DEFAULT NULL,
  `external_summary` VARCHAR(255) NULL DEFAULT NULL,
  `project_id`       BIGINT       NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `REV`),
  CONSTRAINT `FK_DEFECTS_AUD_AUDIT_REVISION_ENTITY`
  FOREIGN KEY (`REV`)
  REFERENCES `AUDIT_REVISION_ENTITY` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT);


CREATE TABLE IF NOT EXISTS `DEFECTS_TEST_EXECUTIONS` (
  `defect_id`         BIGINT NOT NULL,
  `test_execution_id` BIGINT NOT NULL,
  PRIMARY KEY (`defect_id`, `test_execution_id`),
  CONSTRAINT `FK_DEFECT_TEST_EXECUTION`
  FOREIGN KEY (`test_execution_id`)
  REFERENCES `TEST_EXECUTIONS` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_TEST_EXECUTION_DEFECTS`
  FOREIGN KEY (`defect_id`)
  REFERENCES `DEFECTS` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT);

CREATE INDEX `FK_DEFECT_TEST_EXECUTION_idx` ON `DEFECTS_TEST_EXECUTIONS` (`test_execution_id` ASC);


CREATE TABLE IF NOT EXISTS `DEFECTS_TEST_EXECUTIONS_AUD` (
  `defect_id`         BIGINT  NOT NULL,
  `test_execution_id` BIGINT  NOT NULL,
  `REV`               INT     NOT NULL,
  `REVTYPE`           TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`defect_id`, `test_execution_id`, `REV`),
  CONSTRAINT `DEFECTS_TEST_EXECUTIONS_AUD_AUDIT_REVISION_ENTITY`
  FOREIGN KEY (`REV`)
  REFERENCES `AUDIT_REVISION_ENTITY` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT);

