CREATE TABLE IF NOT EXISTS `NOTIFICATIONS` (
  `id`         BIGINT   AUTO_INCREMENT,
  `type`       TINYINT  NOT NULL,
  `text`       TEXT     NOT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date`   DATETIME NOT NULL,
  `author_id`  BIGINT   NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_NOTIFICATIONS_USERS`
  FOREIGN KEY (`author_id`)
  REFERENCES `USERS` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
);

CREATE INDEX `FK_NOTIFICATIONS_USERS_idx` ON `NOTIFICATIONS` (`author_id` ASC);
