-- Renaming of existing tables
ALTER TABLE TEST_CASES RENAME TO TEST_CASE_VERSIONS;
ALTER TABLE TEST_CASES_AUD RENAME TO TEST_CASE_VERSIONS_AUD;

ALTER TABLE TEST_CASE_VERSIONS_AUD
DROP FOREIGN KEY `FK_TEST_CASES_AUD_AUDIT_REVISION_ENTITY`;

ALTER TABLE TEST_CASE_VERSIONS_AUD
ADD CONSTRAINT `FK_TEST_CASE_VERSIONS_AUD_AUDIT_REVISION_ENTITY`
FOREIGN KEY (`REV`)
REFERENCES `AUDIT_REVISION_ENTITY` (`id`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

-- Create new table TEST_CASES
CREATE TABLE `TEST_CASES` (
  `id` BIGINT AUTO_INCREMENT,
  `version` INTEGER NOT NULL DEFAULT 1,
  `tc_id` VARCHAR(255) NOT NULL,
  `deleted` BOOLEAN NULL DEFAULT FALSE,
  `current_version_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_TEST_CASES_TEST_CASE_VERSIONS`
  FOREIGN KEY (`current_version_id`)
  REFERENCES `TEST_CASE_VERSIONS` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
);

CREATE TABLE `TEST_CASES_AUD` (
  `REV` INT NOT NULL,
  `REVTYPE` TINYINT NULL DEFAULT NULL,
  `id` BIGINT AUTO_INCREMENT,
  `tc_id` VARCHAR(255) NOT NULL,
  `deleted` BOOLEAN NULL DEFAULT FALSE,
  `current_version_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `REV`),
  CONSTRAINT `FK_TEST_CASES_AUD_AUDIT_REVISION_ENTITY`
  FOREIGN KEY (`REV`)
  REFERENCES `AUDIT_REVISION_ENTITY` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
);

-- Adding reference from TEST_CASE_VERSIONS to TEST_CASES
ALTER TABLE `TEST_CASE_VERSIONS` ADD COLUMN `test_case_id` BIGINT;
ALTER TABLE `TEST_CASE_VERSIONS` ADD CONSTRAINT `FK_TEST_CASE_VERSIONS_TEST_CASE`
FOREIGN KEY (`test_case_id`)
REFERENCES `TEST_CASES` (`id`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

ALTER TABLE TEST_CASE_VERSIONS_AUD ADD COLUMN `test_case_id` BIGINT;

-- Pre-populate TEST_CASES table and make column mandatory
INSERT INTO `TEST_CASES` (`tc_id`, `deleted`, `current_version_id`)
  SELECT T.`tc_id`, T.`deleted`, T.`id`
  FROM `TEST_CASE_VERSIONS` T;

UPDATE `TEST_CASE_VERSIONS` SET `test_case_id` =
(SELECT `id` FROM `TEST_CASES` WHERE `current_version_id` = `TEST_CASE_VERSIONS`.`id`);

-- Remove tc_id field from TEST_CASE_VERSIONS
ALTER TABLE TEST_CASE_VERSIONS DROP COLUMN `tc_id`;
ALTER TABLE TEST_CASE_VERSIONS_AUD DROP COLUMN `tc_id`;

-- Add sequence_number column
ALTER TABLE TEST_CASE_VERSIONS ADD COLUMN `sequence_number` BIGINT NOT NULL DEFAULT 1;
ALTER TABLE TEST_CASE_VERSIONS_AUD ADD COLUMN `sequence_number` BIGINT;
CREATE UNIQUE INDEX `UK_TEST_CASE_VERSIONS_SEQUENCE` ON `TEST_CASE_VERSIONS` (`test_case_id` ASC, `sequence_number` DESC);
