ALTER TABLE `TEST_STEPS_AUD` DROP `result`;

CREATE TABLE IF NOT EXISTS `VERIFY_STEP_EXECUTIONS` (
  `id`                  BIGINT      AUTO_INCREMENT,
  `verify_step_id`      BIGINT      NOT NULL,
  `test_execution_id`   BIGINT      NOT NULL,
  `created_at`          TIMESTAMP   NOT NULL,
  `actual_result`       TEXT        NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_VERIFY_STEP_EXECUTIONS_VERIFY_STEPS`
  FOREIGN KEY (`verify_step_id`)
  REFERENCES `VERIFY_STEPS` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_VERIFY_STEP_EXECUTIONS_TEST_EXECUTIONS`
  FOREIGN KEY (`test_execution_id`)
  REFERENCES `TEST_EXECUTIONS` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS `VERIFY_STEP_EXECUTIONS_AUD` (
  `id`                  BIGINT      AUTO_INCREMENT,
  `verify_step_id`      BIGINT      NOT NULL,
  `test_execution_id`   BIGINT      NOT NULL,
  `created_at`          TIMESTAMP   NOT NULL,
  `actual_result`       TEXT        NULL DEFAULT NULL,
  `REV` INT NOT NULL,
  `REVTYPE` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `REV`),
  CONSTRAINT `FK_VERIFY_STEP_EXECUTIONS_AUD_AUDIT_REVISION_ENTITY`
  FOREIGN KEY (`REV`)
  REFERENCES `AUDIT_REVISION_ENTITY` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
);


