ALTER TABLE `TEST_CASES` DROP COLUMN `version`;
-- No `version` column in `TEST_CASES_AUD`
ALTER TABLE `TEST_CASE_VERSIONS` DROP COLUMN `version`;
ALTER TABLE `TEST_CASE_VERSIONS_AUD` DROP COLUMN `version`;
