-- Comments 'Posts' and 'PostThreads' tables
CREATE TABLE IF NOT EXISTS `POST_THREADS` (
  `ID`              BIGINT NOT NULL AUTO_INCREMENT,
  `OBJECT_ID`       BIGINT NOT NULL,
  `OBJECT_NAME_REF` BIGINT NULL,
  `FIELD_NAME_REF`  BIGINT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `UNIQUE_THREAD` (`OBJECT_ID` ASC, `OBJECT_NAME_REF` ASC, `FIELD_NAME_REF` ASC)
);

CREATE TABLE IF NOT EXISTS `POST_THREADS_AUD` (
  `ID`              BIGINT  NOT NULL,
  `OBJECT_ID`       BIGINT  NOT NULL,
  `OBJECT_NAME_REF` BIGINT  NULL,
  `FIELD_NAME_REF`  BIGINT  NULL,
  `REV`             INT     NOT NULL,
  `REVTYPE`         TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `REV`),
  CONSTRAINT `FK_POST_THREADS_AUD_AUDIT_REVISION_ENTITY`
  FOREIGN KEY (`REV`)
  REFERENCES `AUDIT_REVISION_ENTITY` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
);


CREATE TABLE IF NOT EXISTS `POSTS` (
  `ID`         BIGINT    NOT NULL AUTO_INCREMENT,
  `MESSAGE`    TEXT      NULL,
  `AUTHOR_ID`  BIGINT    NOT NULL,
  `THREAD_ID`  BIGINT    NOT NULL,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_DELETED` BOOLEAN   NOT NULL DEFAULT FALSE,
  `DELETED_AT` TIMESTAMP NULL     DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_POST_THREADS`
  FOREIGN KEY (`THREAD_ID`)
  REFERENCES `POST_THREADS` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_USERS`
  FOREIGN KEY (`AUTHOR_ID`)
  REFERENCES `USERS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS `POSTS_AUD` (
  `ID`         BIGINT    NOT NULL,
  `MESSAGE`    TEXT      NULL,
  `AUTHOR_ID`  BIGINT    NOT NULL,
  `THREAD_ID`  BIGINT    NOT NULL,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `IS_DELETED` BOOLEAN   NOT NULL DEFAULT FALSE,
  `DELETED_AT` TIMESTAMP NULL     DEFAULT NULL,
  `REV`        INT       NOT NULL,
  `REVTYPE`    TINYINT   NULL     DEFAULT NULL,
  PRIMARY KEY (`ID`, `REV`),
  CONSTRAINT `FK_POSTS_AUD_AUDIT_REVISION_ENTITY`
  FOREIGN KEY (`REV`)
  REFERENCES `AUDIT_REVISION_ENTITY` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
);
