-- Table `DEFECTS`
ALTER TABLE `RELEASES`
ADD COLUMN `deleted` BOOLEAN NULL DEFAULT FALSE;

ALTER TABLE `RELEASES`
ADD COLUMN `name` VARCHAR(255) NULL DEFAULT NULL;

ALTER TABLE `RELEASES`
ADD COLUMN `product_id` BIGINT NULL DEFAULT NULL;

ALTER TABLE `RELEASES`
ADD COLUMN `migrated` BOOLEAN NULL DEFAULT FALSE;

ALTER TABLE `RELEASES`
  ADD CONSTRAINT `FK_RELEASE_PRODUCT`
  FOREIGN KEY (`product_id`)
  REFERENCES `PRODUCTS` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;

INSERT INTO `RELEASES` (`id`, `external_id`, `deleted`, `name`, `product_id`, `migrated`) VALUES (1, 'default', FALSE, 'Default', NULL, TRUE);

CREATE TABLE IF NOT EXISTS `RELEASES_AUD` (
  `REV`              INT          NOT NULL,
  `REVTYPE`          TINYINT      NULL DEFAULT NULL,
  `id`               BIGINT,
  `deleted`          BOOLEAN      NULL DEFAULT FALSE,
  `external_id`      VARCHAR(255) NOT NULL,
  `name`   VARCHAR(255) NULL DEFAULT NULL,
  `product_id`       BIGINT       NULL DEFAULT NULL,
  `migrated`          BOOLEAN      NULL DEFAULT FALSE,
  PRIMARY KEY (`id`, `REV`),
  CONSTRAINT `FK_RELEASES_AUD_AUDIT_REVISION_ENTITY`
  FOREIGN KEY (`REV`)
  REFERENCES `AUDIT_REVISION_ENTITY` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT);
