ALTER TABLE `POSTS` DROP FOREIGN KEY `FK_POST_THREADS`;

ALTER TABLE `POSTS` DROP COLUMN `THREAD_ID`;


ALTER TABLE `POSTS` ADD COLUMN `OBJECT_NAME_REF` BIGINT(20) NOT NULL;
ALTER TABLE `POSTS` ADD COLUMN `OBJECT_ID` BIGINT(20) NOT NULL;
ALTER TABLE `POSTS` ADD INDEX `OBJECT_ID_IDX` (`OBJECT_ID` ASC);
ALTER TABLE `POSTS` ADD INDEX `OBJECT_NAME_REF_IDX` (`OBJECT_NAME_REF` ASC);

ALTER TABLE `POSTS_AUD` ADD COLUMN `OBJECT_NAME_REF` BIGINT(20) NOT NULL;
ALTER TABLE `POSTS_AUD` ADD COLUMN `OBJECT_ID` BIGINT(20) NOT NULL;


DROP TABLE `POST_THREADS`;
DROP TABLE `POST_THREADS_AUD`;
