-- Table `REQUIREMENT_TEST_CASES`
CREATE TABLE IF NOT EXISTS `REQUIREMENT_TEST_CASES` (
  `requirement_id` BIGINT NOT NULL,
  `test_case_id` BIGINT NOT NULL,
  PRIMARY KEY (`requirement_id`, `test_case_id`),
  CONSTRAINT `FK_REQUIREMENT_TEST_CASES`
    FOREIGN KEY (`test_case_id`)
    REFERENCES `TEST_CASES` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_TEST_CASE_REQUIREMENTS`
    FOREIGN KEY (`requirement_id`)
    REFERENCES `REQUIREMENTS` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT);

CREATE INDEX `FK_REQUIREMENT_TEST_CASES_idx` ON `REQUIREMENT_TEST_CASES` (`test_case_id` ASC);


-- Table `REQUIREMENT_TEST_CASES_AUD`
CREATE TABLE IF NOT EXISTS `REQUIREMENT_TEST_CASES_AUD` (
  `REV` INT NOT NULL,
  `requirement_id` BIGINT NOT NULL,
  `test_case_id` BIGINT NOT NULL,
  `REVTYPE` TINYINT NULL,
  PRIMARY KEY (`REV`, `requirement_id`, `test_case_id`),
  CONSTRAINT `FK_REQUIREMENT_TESTS_AUD_AUDIT_REVISION_ENTITY`
    FOREIGN KEY (`REV`)
    REFERENCES `AUDIT_REVISION_ENTITY` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT);


-- Migrate `TEST_CASES` and `REQUIREMENTS` relationships
INSERT INTO `REQUIREMENT_TEST_CASES` (`test_case_id`, `requirement_id`) SELECT `id`, `requirement_id` FROM `TEST_CASES` WHERE `requirement_id` is not null;;


-- Rebuild indices for table `TEST_CASES`
ALTER TABLE `TEST_CASES` DROP INDEX `UK_TEST_CASES`;
ALTER TABLE `TEST_CASES` DROP FOREIGN KEY `FK_TEST_CASES_REQUIREMENTS`;
ALTER TABLE `TEST_CASES` DROP INDEX `FK_TEST_CASES_REQUIREMENTS_idx`;
ALTER TABLE `TEST_CASES` DROP `requirement_id`;
ALTER TABLE `TEST_CASES_AUD` DROP `requirement_id`;
