CREATE TABLE IF NOT EXISTS `FILE_STORAGE` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `deleted` BOOLEAN NULL DEFAULT FALSE,
  `tc_id` BIGINT NOT NULL,
  `filename` TEXT NULL DEFAULT NULL,
  `created` VARCHAR(255) NOT NULL,
  `location` TEXT NOT NULL,
  `author` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
   CONSTRAINT `FK_TEST_CASES_FILE_STORAGE`
    FOREIGN KEY (`tc_id`)
    REFERENCES `TEST_CASES` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT);


CREATE TABLE IF NOT EXISTS `FILE_STORAGE_AUD` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `deleted` BOOLEAN NULL DEFAULT FALSE,
  `tc_id` BIGINT NOT NULL,
  `filename` TEXT NULL DEFAULT NULL,
  `created` VARCHAR(255) NOT NULL,
  `location` TEXT NOT NULL,
  `author` VARCHAR(255) NOT NULL,
  `REV`         INT          NOT NULL,
  `REVTYPE`     TINYINT      NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `REV`),
  CONSTRAINT `FK_FILE_STORAGE_AUD_AUDIT_REVISION_ENTITY`
  FOREIGN KEY (`REV`)
  REFERENCES `AUDIT_REVISION_ENTITY` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
);

