CREATE TABLE IF NOT EXISTS `DROPS` (
  `id`        BIGINT(20)   NOT NULL AUTO_INCREMENT,
  `name`      VARCHAR(255) NOT NULL,
  `product_id` BIGINT(20)   NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_DROP_PRODUCT` (`product_id`),
  CONSTRAINT `FK_DROP_PRODUCT` FOREIGN KEY (`product_id`) REFERENCES `PRODUCTS` (`id`)
);

CREATE TABLE IF NOT EXISTS `DROPS_AUD` (
  `id`        BIGINT(20)   NOT NULL AUTO_INCREMENT,
  `name`      VARCHAR(255) NOT NULL,
  `product_id` BIGINT(20)   NOT NULL,
  `REV` INT NOT NULL,
  `REVTYPE` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `REV`),
  CONSTRAINT `FK_DROPS_AUD_AUDIT_REVISION_ENTITY` FOREIGN KEY (`REV`) REFERENCES `AUDIT_REVISION_ENTITY` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS `ISOS` (
  `id`      BIGINT(20)   NOT NULL AUTO_INCREMENT,
  `name`    VARCHAR(255) NOT NULL,
  `version` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_ISO_NAME_VERSION` (`name`, `version`)
);

CREATE TABLE IF NOT EXISTS `ISOS_AUD` (
  `id`      BIGINT(20)   NOT NULL AUTO_INCREMENT,
  `name`    VARCHAR(255) NOT NULL,
  `version` VARCHAR(255) NOT NULL,
  `REV` INT NOT NULL,
  `REVTYPE` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `REV`),
  CONSTRAINT `FK_ISOS_AUD_AUDIT_REVISION_ENTITY` FOREIGN KEY (`REV`) REFERENCES `AUDIT_REVISION_ENTITY` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS `ISOS_DROPS` (
  `id`     BIGINT(20) NOT NULL AUTO_INCREMENT,
  `iso_id`  BIGINT(20) NOT NULL,
  `drop_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_ISOS_DROPS_ISO` (`iso_id`),
  CONSTRAINT `FK_ISOS_DROPS_ISO` FOREIGN KEY (`iso_id`) REFERENCES `ISOS` (`id`),
  KEY `FK_ISOS_DROPS_DROPS` (`drop_id`),
  CONSTRAINT `FK_ISOS_DROPS_DROPS` FOREIGN KEY (`drop_id`) REFERENCES `DROPS` (`id`),
  UNIQUE KEY `UK_ISO_ID_DROP_ID` (`drop_id`, `iso_id`)
);

CREATE TABLE IF NOT EXISTS `ISOS_DROPS_AUD` (
  `id`     BIGINT(20) NOT NULL AUTO_INCREMENT,
  `iso_id`  BIGINT(20) NOT NULL,
  `drop_id` BIGINT(20) NOT NULL,
  `REV` INT NOT NULL,
  `REVTYPE` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `REV`),
  CONSTRAINT `FK_ISOS_DROPS_AUD_AUDIT_REVISION_ENTITY` FOREIGN KEY (`REV`) REFERENCES `AUDIT_REVISION_ENTITY` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
);



