ALTER TABLE `TEST_PLANS` DROP FOREIGN KEY `FK_TEST_PLAN_RELEASE`;
ALTER TABLE `REQUIREMENTS` DROP FOREIGN KEY `FK_REQUIREMENTS_RELEASES`;
ALTER TABLE `REQUIREMENTS` DROP INDEX `FK_REQUIREMENTS_RELEASES_idx`;

ALTER TABLE `TEST_PLANS` DROP `release_id`;
ALTER TABLE `REQUIREMENTS` DROP `release_id`;

DROP TABLE `RELEASES`;
DROP TABLE `RELEASES_AUD`;
