ALTER TABLE `TEST_EXECUTIONS` ADD COLUMN `iso_id` BIGINT NULL DEFAULT NULL;
ALTER TABLE `TEST_EXECUTIONS_AUD` ADD COLUMN `iso_id` BIGINT NULL DEFAULT NULL;

ALTER TABLE `DROPS` ADD COLUMN `default_drop` TINYINT NOT NULL DEFAULT FALSE;
ALTER TABLE `DROPS_AUD` ADD COLUMN `default_drop` TINYINT NOT NULL DEFAULT FALSE;
