ALTER TABLE `TEST_CASE_VERSIONS` ADD `intrusive` BIT DEFAULT FALSE;
ALTER TABLE `TEST_CASE_VERSIONS` ADD `intrusive_comment` VARCHAR(255);

ALTER TABLE `TEST_CASE_VERSIONS_AUD` ADD `intrusive` BIT DEFAULT FALSE;
ALTER TABLE `TEST_CASE_VERSIONS_AUD` ADD `intrusive_comment` VARCHAR(255);