CREATE TABLE IF NOT EXISTS `TEST_CASE_VERSIONS_TECHNICAL_COMPONENTS` (
  `id`                      BIGINT(20) NOT NULL AUTO_INCREMENT,
  `test_case_version_id`    BIGINT(20) NOT NULL,
  `technical_component_id`  BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_TC_VERSIONS_TECHNICAL_COMPONENTS_TEST_CASE` FOREIGN KEY (`test_case_version_id`) REFERENCES `TEST_CASE_VERSIONS` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_TC_VERSIONS_TECHNICAL_COMPONENTS_COMPONENT` FOREIGN KEY (`technical_component_id`) REFERENCES `TECHNICAL_COMPONENTS` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  UNIQUE KEY `UK_TC_VERSION_ID_TECHNICAL_COMPONENT_ID` (`test_case_version_id`, `technical_component_id`)
);

CREATE TABLE IF NOT EXISTS `TEST_CASE_VERSIONS_TECHNICAL_COMPONENTS_AUD` (
  `id`                     BIGINT(20) NOT NULL AUTO_INCREMENT,
  `test_case_version_id`   BIGINT(20) NOT NULL,
  `technical_component_id` BIGINT(20) NOT NULL,
  `REV` INT NOT NULL,
  `REVTYPE` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `REV`),
  CONSTRAINT `FK_TC_VERSIONS_TECHNICAL_COMPONENTS_AUD_AUDIT_REVISION_ENTITY` FOREIGN KEY (`REV`) REFERENCES `AUDIT_REVISION_ENTITY` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
);

INSERT INTO TEST_CASE_VERSIONS_TECHNICAL_COMPONENTS (test_case_version_id, technical_component_id) SELECT id, technical_component_id FROM TEST_CASE_VERSIONS;

ALTER TABLE `TEST_CASE_VERSIONS` DROP FOREIGN KEY `FK_TEST_CASES_TECHNICAL_COMPONENTS`;
ALTER TABLE `TEST_CASE_VERSIONS` DROP INDEX `FK_TEST_CASES_TECHNICAL_COMPONENTS_idx`;
ALTER TABLE `TEST_CASE_VERSIONS` DROP `technical_component_id`;

ALTER TABLE `TEST_CASE_VERSIONS_AUD` DROP `technical_component_id`;