CREATE TABLE IF NOT EXISTS `TEST_PLANS` (
  `id`          BIGINT       AUTO_INCREMENT,
  `deleted`     BOOLEAN      NULL DEFAULT FALSE,
  `name`        VARCHAR(255) NOT NULL,
  `description` LONGTEXT     NULL DEFAULT NULL,
  `environment` VARCHAR(255) NULL DEFAULT NULL,
  `release_number`     VARCHAR(255) NULL DEFAULT NULL,
  `project_id`  BIGINT       NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_TEST_PLANS_PROJECTS`
  FOREIGN KEY (`project_id`)
  REFERENCES `PROJECTS` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT);

CREATE INDEX `FK_TEST_PLANS_PROJECTS_idx` ON `TEST_PLANS` (`project_id` ASC);

CREATE TABLE IF NOT EXISTS `TEST_PLANS_AUD` (
  `id`          BIGINT       AUTO_INCREMENT,
  `deleted`     BOOLEAN      NULL DEFAULT FALSE,
  `name`        VARCHAR(255) NOT NULL,
  `description` LONGTEXT     NULL DEFAULT NULL,
  `environment` VARCHAR(255) NULL DEFAULT NULL,
  `release_number`     VARCHAR(255) NULL DEFAULT NULL,
  `project_id`  BIGINT       NULL DEFAULT NULL,
  `REV`         INT          NOT NULL,
  `REVTYPE`     TINYINT      NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `REV`),
  CONSTRAINT `TEST_PLANS_AUD_AUDIT_REVISION_ENTITY`
  FOREIGN KEY (`REV`)
  REFERENCES `AUDIT_REVISION_ENTITY` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT);

CREATE INDEX `TEST_PLANS_AUD_AUDIT_REVISION_ENTITY_idx` ON `TEST_CASES_AUD` (`REV` ASC);

CREATE TABLE IF NOT EXISTS `TEST_PLANS_TEST_CASES` (
  `test_plan_id` BIGINT NOT NULL,
  `test_case_id` BIGINT NOT NULL,
  PRIMARY KEY (`test_plan_id`, `test_case_id`),
  CONSTRAINT `FK_TEST_PLANS_TEST_CASES`
  FOREIGN KEY (`test_case_id`)
  REFERENCES `TEST_CASES` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_TEST_CASES_TEST_PLANS`
  FOREIGN KEY (`test_plan_id`)
  REFERENCES `TEST_PLANS` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT);

CREATE INDEX `FK_TEST_PLANS_TEST_CASES_idx` ON `TEST_PLANS_TEST_CASES` (`test_plan_id` ASC);
CREATE INDEX `FK_TEST_CASES_TEST_PLANS_idx` ON `TEST_PLANS_TEST_CASES` (`test_case_id` ASC);

CREATE TABLE IF NOT EXISTS `TEST_PLANS_TEST_CASES_AUD` (
  `test_plan_id` BIGINT  NOT NULL,
  `test_case_id` BIGINT  NOT NULL,
  `REV`          INT     NOT NULL,
  `REVTYPE`      TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`test_plan_id`, `test_case_id`, `REV`),
  CONSTRAINT `TEST_PLANS_TEST_CASES_AUD_AUDIT_REVISION_ENTITY`
  FOREIGN KEY (`REV`)
  REFERENCES `AUDIT_REVISION_ENTITY` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT);