CREATE TABLE IF NOT EXISTS `TEST_CASES_SUBSCRIBERS` (
  `id`                    BIGINT NOT NULL AUTO_INCREMENT,
  `test_case_id`          BIGINT NOT NULL,
  `user_id`               BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_TEST_CASES_SUBSCRIBERS_TEST_CASES` FOREIGN KEY (`test_case_id`) REFERENCES `TEST_CASES` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_TEST_CASES_SUBSCRIBERS_USERS` FOREIGN KEY (`user_id`) REFERENCES `USERS` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  UNIQUE KEY `UK_TEST_CASE_SUBSCRIBER` (`test_case_id`, `user_id`)
);

CREATE TABLE IF NOT EXISTS `TEST_CASES_SUBSCRIBERS_AUD` (
  `id`                    BIGINT NOT NULL AUTO_INCREMENT,
  `test_case_id`          BIGINT NOT NULL,
  `user_id`               BIGINT NOT NULL,
  `REV`                   INT NOT NULL,
  `REVTYPE`               TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `REV`),
  CONSTRAINT `FK_TEST_CASES_SUBSCRIBERS_AUD_AUDIT_REVISION_ENTITY` FOREIGN KEY (`REV`) REFERENCES `AUDIT_REVISION_ENTITY` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
);