ALTER TABLE `TEST_PLANS` ADD COLUMN `author_id` BIGINT NULL DEFAULT NULL;
ALTER TABLE `TEST_PLANS_AUD` ADD COLUMN `author_id` BIGINT NULL DEFAULT NULL;

ALTER TABLE `TEST_PLANS` ADD CONSTRAINT `FK_TEST_CAMPAIGN_AUTHOR` FOREIGN KEY (`author_id`) REFERENCES `USERS` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;


ALTER TABLE `TEST_CAMPAIGN_GROUP` ADD CONSTRAINT `FK_TEST_CAMPAIGN_GROUP_AUTHOR` FOREIGN KEY (`author_id`) REFERENCES `USERS` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;