ALTER TABLE `TEST_CASES` ADD COLUMN `test_case_status` INTEGER;
ALTER TABLE `TEST_CASES_AUD` ADD COLUMN `test_case_status` INTEGER;
ALTER TABLE `TEST_CASES` ADD COLUMN `version` INTEGER;
ALTER TABLE `TEST_CASES_AUD` ADD COLUMN `version` INTEGER;
UPDATE `TEST_CASES` SET `version` = 1;